# Generated by Django 3.1.2 on 2024-03-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('date', models.DateField()),
                ('available', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_nights', models.IntegerField()),
                ('maximum_nights', models.IntegerField()),
            ],
        ),
    ]
